version: '2'
services:
  novel:
    image: registry.gitlab.com/honglian/novelweb
    container_name: ahuang_novel
    environment:
      - DB_HOST=172.16.10.78
      - DB_PORT=3306
      - DB_NAME=novel
      - DB_PWD=123456
      - DB_USER=root
      - REDIS_HOST=104.168.236.234
      - REDIS_PORT=6379
      - REDIS_PWD=
      - REDIS_DB=6
    volumes:
      - ./rule:/app/rule
    ports:
      - "8900:8900"