version: '2'
services:
  novel:
    image: registry.gitlab.com/honglian/novelweb
    container_name: ahuang_novel
    environment:
      - DB_HOST=127.0.0.1
      - DB_PORT=3306
      - DB_NAME=novel
      - DB_PWD=123456
      - DB_USER=root
    volumes:
      - ./rule:/app/rule
    ports:
      - "8900:8900"