version: '2'
services:
  novel:
    image: registry.gitlab.com/honglian/novelweb
    container_name: ahuang_novel
    environment:
      - DB_HOST=172.16.10.78
      - DB_PORT=3306
      - DB_NAME=novel
      - DB_PWD=123456
    ports:
      - "8900:8900"